name: Build and Test WasmEdge on riscv64 arch

concurrency:
  group: build-riscv64-aot-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/riscv_aot.yml"

jobs:
  build_riscv64_pre:
    name: riscv64_pre
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: pull WasmEdge
      run: |
        sudo apt-get install --no-install-recommends qemu-user-static binfmt-support
        update-binfmts --enable qemu-riscv64
        update-binfmts --display qemu-riscv64
        sudo chmod a+x /usr/bin/qemu-*
  build_riscv64:
    name: riscv64
    runs-on: ubuntu-latest
    needs: build_riscv64_pre
    container:
      image: riscv64/ubuntu:21.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: pull WasmEdge
      run: |
        apt-get install git
        apt-get install libatomic

        
