name: Build and Test WasmEdge on riscv64 arch

concurrency:
  group: build-riscv64-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/riscv.yml"

jobs:
  build_riscv64:
    name: riscv64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install riscv toolchain
      run: |
        sudo apt install autoconf automake autotools-dev curl libmpc-dev libmpfr-dev libgmp-dev \
                 gawk build-essential bison flex texinfo gperf libtool patchutils bc \
                 zlib1g-dev libexpat-dev git \
                 libglib2.0-dev libfdt-dev libpixman-1-dev \
                 libncurses5-dev libncursesw5-dev
        mkdir riscv64-linux
        cd riscv64-linux
        git clone https://gitee.com/mirrors/riscv-gnu-toolchain
        cd riscv-gnu-toolchain
        git rm qemu
        git submodule update --init --recursive
        ./configure --prefix=/opt/riscv64
        sudo make linux -j $(nproc)
        export PATH="$PATH:/opt/riscv64/bin"
        riscv64-unknown-linux-gnu-gcc -v
