name: Build and Test WasmEdge on OpenWrt platform

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build_openwrt:
    name: OpenWrt-x86_64
    runs-on: ubuntu-latest
    container:
      image: ankann/openwrt-wasmedge:openwrt-wasmedge-0.10.0
      options: --privileged
    steps:
#     - name: Install openwrt image
#       run: |
#         docker pull registry.cn-shanghai.aliyuncs.com/suling/openwrt:x86_64
#         docker run --name openwrt -d --privileged registry.cn-shanghai.aliyuncs.com/suling/openwrt:x86_64 /sbin/init
#         docker exec openwrt bash
#         ls /

    - name: Build curl
      run: |
        mkdir /var/lock
        /bin/opkg update
        /bin/opkg search curl
        /bin/opkg install curl
        ls /bin

    - name: Install WasmEdge ipk
      run: |
        curl -sLO  https://github.com/O3Ol/openwrt-build/releases/download/test/WasmEdge_0.10.0_x86_64.ipk -o WasmEdge_0.10.0_x86_64.ipk
        cp WasmEdge_0.10.0_x86_64.ipk /tmp
        
#     - name: Install WasmEdge ipk
#       run: |
#         curl -sLO  https://github.com/O3Ol/openwrt-build/releases/download/openwrt-wasmedge-0.10.0/WasmEdge_0.10.0_x86_64-ipk.tgz -o WasmEdge_0.10.0_x86_64-ipk.tgz
#         tar zxvf WasmEdge_0.10.0_x86_64-ipk.tgz -C /tmp
        
    - name: Build WasmEdge ipk
      run: |
        /bin/opkg install /tmp/WasmEdge_0.10.0_x86_64.ipk
        ls /bin


    - name: Test WasmEdge
      run: |
        wasmedge
